[package]
name = "bowtie"
version = "0.1.0"
authors = ["Michael House <mjhouse@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
rusqlite = "0.20.0"
whirlpool = "0.8.1"
base64 = "0.11.0"
simplelog = "0.7.4"
medallion = "2.3.1"
chrono = "0.4.9"
log = "0.4.8"
serde = { version = "1.0", features = ["derive"] }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["handlebars_templates","serve"]
