[package]
name = "bowtie_routes"
version = "0.1.0"
authors = ["Michael House <mjhouse@protonmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
diesel = { version = "1.0.0", features = ["postgres"] }

bowtie_models = { path = "../models" }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["tera_templates","serve"]